services:
  db:
    image: postgis/postgis:15-3.3
    container_name: brindisi_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=traffico_brindisi
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: brindisi_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build: .
    container_name: brindisi_etl
    volumes:
      - .:/app
    depends_on:
      - db